name: Checks, Build and Deploy

on:
    push:
        branches:
            - main
            - master
            - develop
            - feature/*
            - issue/*

env:
    FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

jobs:
    checks:
        name: Checks
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x]
        steps:
            - uses: actions/checkout@v2
            - run: 'curl -H "Cache-Control: no-cache" https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash'
            - run: yarn setup
            - run: yarn check-pretty
            - run: yarn check-spell
            - run: yarn check-licensing
            - run: yarn check-audit
            - run: yarn lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn setup
            - run: yarn test --coverage
            - run: yarn e2e

    package:
        name: Package
        needs: [Checks, Test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn setup
            - run: echo 'publishing frontend'
            - uses: actions/upload-artifact@v3
              with:
                  name: frontend
                  path: dist/packages/frontend

            - run: echo 'publishing api'
            - uses: actions/upload-artifact@v3
              with:
                  name: api
                  path: dist/packages/api

            - run: echo 'publishing coverage'
            - uses: actions/upload-artifact@v3
              with:
                  name: api
                  path: coverage

            - run: echo 'publishing lighthouse'
            - uses: actions/upload-artifact@v3
              with:
                  name: lighthouse
                  path: reports

            - run: echo 'publishing coveralls'
            - uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: './coverage/lcov.info'

    BuildValidation:
        name: Build-Validation
        needs: [Package]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn setup
            - run: echo 'downloading frontend'
            - run: mkdir -p dist/packages
            - uses: actions/download-artifact@v3
              with:
                  name: frontend
                  path: dist/packages/frontend
            - run: yarn lighthouse
