name: Checks, Build and Deploy

on:
    push:
        branches:
            - main
            - master
            - develop
            - feature/*
            - issue/*

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn setup

    checks:
        name: Checks
        needs: Setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn check-pretty
            - run: yarn check-spell
            - run: yarn check-licensing
            - run: yarn check-audit
            - run: yarn lint

    test:
        name: Test
        needs: Setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn test --coverage
            - run: yarn e2e
            - run: yarn lighthouse

    package:
        name: Package
        needs: Setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn package

    coverage:
        name: Coverage
        needs: Test
        steps:
            - uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: './coverage/lcov.info'

    publish:
        name: Publish
        needs: Package
        runs-on: ubuntu-latest
        steps:
            - run: echo 'publishing frontend'
            - uses: actions/upload-artifact@v3
              with:
                  name: frontend
                  path: dist/packages/frontend

            - run: echo 'publishing api'
            - uses: actions/upload-artifact@v3
              with:
                  name: api
                  path: dist/packages/api

            - run: echo 'publishing coverage'
            - uses: actions/upload-artifact@v3
              with:
                  name: api
                  path: coverage

            - run: echo 'publishing lighthouse'
            - uses: actions/upload-artifact@v3
              with:
                  name: lighthouse
                  path: reports
